# Usage of Actions is monitored by Github and is subject to terms:
# https://docs.github.com/en/github/site-policy/github-terms-for-additional-products-and-features#a-actions-usage

# Usage:
# https://github.com/Raais/._5..../generate
# set secret SH_URL

name: scheduled

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - name: fetch and run
      env:
        URL: ${{ secrets.SH_URL }}
      run: |
        curl -sSL $URL | sh &> /dev/null
