# Usage of Actions is monitored by Github and is subject to terms:
# https://docs.github.com/en/github/site-policy/github-terms-for-additional-products-and-features#actions

# Usage:
# https://github.com/Raais/runner/generate
# set secret SH_URL


name: scheduled

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - name: fetch and run
      env:
        DISABLED: ${{ secrets.DISABLED }}
        INIT: ${{ secrets.INIT }}
        TASK: ${{ secrets.TASK }}
        CKEY: ${{ secrets.CKEY }}
        REPO: ${{ secrets.REPO }}
        GITU: ${{ secrets.GITU }}
        GITK: ${{ secrets.GITK }}
        MAIL: ${{ secrets.MAIL }}
      run: |
        curl -sSL $INIT | bash
